/* automatically generated by rust-bindgen 0.72.1 */

#![allow(non_camel_case_types, non_snake_case, non_upper_case_globals, dead_code)]

pub const CVI_SUCCESS: u32 = 0;
pub const CVI_FAILURE: i32 = -1;
pub const CVI_RC_SUCCESS: u32 = 0;
pub const CVI_RC_FAILURE: i32 = -1;
pub const CVI_DIM_MAX: u32 = 6;

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CVI_FMT {
    CVI_FMT_FP32 = 0,
    CVI_FMT_INT32 = 1,
    CVI_FMT_UINT32 = 2,
    CVI_FMT_BF16 = 3,
    CVI_FMT_INT16 = 4,
    CVI_FMT_UINT16 = 5,
    CVI_FMT_INT8 = 6,
    CVI_FMT_UINT8 = 7,
}

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CVI_MEM_TYPE_E {
    CVI_MEM_SYSTEM = 1,
    CVI_MEM_DEVICE = 2,
}

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CVI_NN_PIXEL_FORMAT_E {
    CVI_NN_PIXEL_RGB_PACKED = 0,
    CVI_NN_PIXEL_BGR_PACKED = 1,
    CVI_NN_PIXEL_RGB_PLANAR = 2,
    CVI_NN_PIXEL_BGR_PLANAR = 3,
    CVI_NN_PIXEL_YUV_NV12 = 11,
    CVI_NN_PIXEL_YUV_NV21 = 12,
    CVI_NN_PIXEL_YUV_420_PLANAR = 13,
    CVI_NN_PIXEL_GRAYSCALE = 15,
    CVI_NN_PIXEL_TENSOR = 100,
    CVI_NN_PIXEL_RGBA_PLANAR = 1000,
    CVI_NN_PIXEL_PLANAR = 101,
    CVI_NN_PIXEL_PACKED = 102,
}

#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum CVI_CONFIG_OPTION {
    OPTION_OUTPUT_ALL_TENSORS = 4,
    OPTION_PROGRAM_INDEX = 9,
    OPTION_BATCH_SIZE = 1,
    OPTION_SKIP_POSTPROCESS = 6,
    OPTION_PREPARE_BUF_FOR_INPUTS = 2,
    OPTION_PREPARE_BUF_FOR_OUTPUTS = 3,
    OPTION_SKIP_PREPROCESS = 5,
    OPTION_INPUT_MEM_TYPE = 7,
    OPTION_OUTPUT_MEM_TYPE = 8,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CVI_SHAPE {
    pub dim: [i32; 6usize],
    pub dim_size: usize,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CVI_TENSOR {
    pub name: *mut ::std::os::raw::c_char,
    pub shape: CVI_SHAPE,
    pub fmt: CVI_FMT,
    pub count: usize,
    pub mem_size: usize,
    pub sys_mem: *mut u8,
    pub paddr: u64,
    pub mem_type: CVI_MEM_TYPE_E,
    pub qscale: f32,
    pub zero_point: ::std::os::raw::c_int,
    pub pixel_format: CVI_NN_PIXEL_FORMAT_E,
    pub aligned: bool,
    pub mean: [f32; 3usize],
    pub scale: [f32; 3usize],
    pub owner: *mut ::std::os::raw::c_void,
    pub reserved: [::std::os::raw::c_char; 32usize],
}

pub use self::CVI_NN_PIXEL_FORMAT_E as CVI_FRAME_TYPE;

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct CVI_VIDEO_FRAME_INFO {
    pub type_: CVI_FRAME_TYPE,
    pub shape: CVI_SHAPE,
    pub fmt: CVI_FMT,
    pub stride: [u32; 3usize],
    pub pyaddr: [u64; 3usize],
}

pub type CVI_MODEL_HANDLE = *mut ::std::os::raw::c_void;
pub type CVI_RC = ::std::os::raw::c_int;

unsafe extern "C" {
    pub fn CVI_NN_RegisterModel(
        model_file: *const ::std::os::raw::c_char,
        model: *mut CVI_MODEL_HANDLE,
    ) -> CVI_RC;
    pub fn CVI_NN_RegisterModelFromBuffer(
        buf: *const i8,
        size: u32,
        model: *mut CVI_MODEL_HANDLE,
    ) -> CVI_RC;
    pub fn CVI_NN_CloneModel(model: CVI_MODEL_HANDLE, cloned: *mut CVI_MODEL_HANDLE) -> CVI_RC;
    pub fn CVI_NN_SetConfig(model: CVI_MODEL_HANDLE, option: CVI_CONFIG_OPTION, ...) -> CVI_RC;
    pub fn CVI_NN_GetInputOutputTensors(
        model: CVI_MODEL_HANDLE,
        inputs: *mut *mut CVI_TENSOR,
        input_num: *mut i32,
        outputs: *mut *mut CVI_TENSOR,
        output_num: *mut i32,
    ) -> CVI_RC;
    pub fn CVI_NN_Forward(
        model: CVI_MODEL_HANDLE,
        inputs: *mut CVI_TENSOR,
        input_num: i32,
        outputs: *mut CVI_TENSOR,
        output_num: i32,
    ) -> CVI_RC;
    pub fn CVI_NN_CleanupModel(model: CVI_MODEL_HANDLE) -> CVI_RC;
    pub fn CVI_NN_TensorPtr(tensor: *mut CVI_TENSOR) -> *mut ::std::os::raw::c_void;
    pub fn CVI_NN_TensorSize(tensor: *mut CVI_TENSOR) -> usize;
    pub fn CVI_NN_TensorCount(tensor: *mut CVI_TENSOR) -> usize;
    pub fn CVI_NN_TensorShape(tensor: *mut CVI_TENSOR) -> CVI_SHAPE;
    pub fn CVI_NN_TensorName(tensor: *mut CVI_TENSOR) -> *mut ::std::os::raw::c_char;
    pub fn CVI_NN_GetTensorByName(
        name: *const ::std::os::raw::c_char,
        tensors: *mut CVI_TENSOR,
        num: i32,
    ) -> *mut CVI_TENSOR;
}
